server:
  port: 8001
 
# datasource
spring:
  application:
    name: cloud-provide
  datasource:
    url: jdbc:mysql://localhost:3306/cloud01?Unicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 使用druid connection pool
    dbcp2:
      min-idle: 5                             # 数据库连接池的最小维持连接数
      initial-size: 5                         # 初始化连接数
      max-total: 5                            # 最大连接数
      max-wait-millis: 200                    # 等待连接获取的最大超时时间

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mql.springcloud.entity
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  
  instance:
    instanceId: cloud-provide-8001
    preferIpAddress: true #显示IP地址而不是主机名
    
    
info: 
  app.name: cloud-provide-8001
  company.name: www.mql.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
 

  