server:
  port: 7003
  
eureka:
  instance:
    hostname: eureka7003.com
  client:
    registerWithEureka: false        #false表示不向注册中心注册自己。
    fetchRegistry: false             #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/