server: 
  port: 6001

spring:
  application: 
    name: zuul-6001

#指定注册中心地址   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance: 
    prefer-ip-address:true

#自定义路由映射
zuul:
  routes:
    cloud-provide:  /apigateway/**

